[core]
copyFrom:ROOT:地球联合政府/坦克/装甲单位模板.ini,ROOT:unit-behaviors.template
name:基地车
displayText:基地车
displayText_ja:MCV
displayDescription:[装甲][无法攻击]\n-可以展开成基地
displayDescription_ja = [アーマー] [攻撃できない] \ n-canをベースに発展させる
mass:1000
price:4000
maxHp:2000
radius:20
buildSpeed:30s
dieOnConstruct:true
nanoRange:20
isBuilder:true
transportSlotsNeeded:4


[graphics]
image:基地车.png
scaleImagesTo:50
turretImageScale:1.5
dustEffect:true



[attack]
canAttack:false


[movement]
movementType:LAND
moveSpeed:0.6
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
reverseSpeedPercentage:0.4
maxTurnSpeed:4
turnAcceleration:1.2
moveSlidingMode:1


[action_1]
pos:0.1
text:展开
whenBuilding_rotateTo:270
convertTo:指挥中心
addResources:unsetFlag=1
whenBuilding_cannotMove:true
buildSpeed:5s
#[action_stop_forAi]
#text:停下当前行动
#autoTrigger:if self.isControlledByAI() and self.hp(lessThan=1500)
#
#alsoQueueAction:run_forAi

[action_run_forAi]
pos:0.11
text:离开危险的战场
clearAllWaypoints:true
autoTrigger:if self.isControlledByAI() and self.hp(lessThan=1500) and not self.hasFlag(id=1)
addResources:setFlag=1
alsoQueueAction:1
alsoTriggerOrQueueActionConditional:if not self.hasActiveWaypoint(type='touchTarget')

isVisible:false
addWaypoint_type:touchTarget
addWaypoint_target_nearestUnit_team:own
addWaypoint_target_nearestUnit_tagged:repair
