[core]
copyFrom:ROOT:地球联合政府/步兵/t1步兵基础/t1步兵基础.ini,ROOT:unit-behaviors.template
name:t1火箭步兵
displayText:火箭步兵
displayText_ja:対装甲擲弾兵
displayDescription:[对地][对空][反装甲/空军]\n-前期反装甲步兵,对装甲单位有3倍的伤害加成\n-速度较慢,需要一定技巧才能追上地方机动单位
displayDescription_ja = [配達] [皇帝エア] [反装甲/空軍] \ n対アモルド歩兵の初期段階、装甲ユニットの3倍のダメージボーナス\ n-slower速度では、追いつくために特定のスキルが必要です地元のモーターユニットと一緒に地元のモーターユニットに追いつく。
price:120
maxHp:200
buildSpeed:12s
[graphics]
image_turret:火箭筒.png
turretImageScale:0.8




[attack]
maxAttackRange:140
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true
#isMelee:true
#meleeEngangementDistance:90


[turret_1]
x:0
y:0
shoot_sound:missile_fire
shoot_light:#FF000000
recoilOffset:-3
recoilOutTime:2
recoilReturnTime:30
delay:180
aimOffsetSpread:0.1

[projectile_1]
life:1000
targetGround:false
largeHitEffect:true
directDamage:80
mutator1_ifUnitWithTags:tank
mutator1_directDamageMultiplier:2
targetSpeed:6
image:抛射体2.png
speed:1
targetSpeedAcceleration:0.3

shouldRevealFog:true
trailEffect:true


[movement]
moveSpeed:0.6
