[core]
copyFrom          : ROOT:地球联合政府/步兵/t1步兵基础/t1步兵基础.ini,ROOT:unit-behaviors.template
name              : 辐射步兵
displayText       : 辐射步兵
displayDescription: [对地][反步兵/装甲]\n-手持高能辐射枪的步兵, 他们手上的玛辛射线发射器能让步兵感受痛楚\n-对步兵高伤害, 可以将坦克变为无人状态
displayDescription_ja = [地球] [抗侵入者/鎧] \ n-in-in-fantry with High-Energy Radiation Guns、Masinは、ブイーズが痛みを感じることができると言われています。
maxHp             : 500
buildSpeed        : 5s
price             : 800


[graphics]
image_turret:辐射枪.png
turretImageScale:0.6




[attack]
maxAttackRange          : 130
canAttack               : true
canAttackFlyingUnits    : false
canAttackLandUnits      : true
canAttackUnderwaterUnits: false
showRangeUIGuide        : true
#isMelee                 : true
#meleeEngangementDistance: 150
aimOffsetSpread         : 0
canOnlyAttackUnitsWithTags:tank,lives,SPARK

[turret_1]
x               : 0
y               : 5
shoot_light     : #FF000000
recoilOffset    : -3
recoilOutTime   : 2
recoilReturnTime: 10
delay           : 30
shoot_sound_vol : 2
onShoot_freezeBodyMovementFor:0.5s

shoot_sound        : 辐射.wav


[projectile_1]
life               : 30
friendlyFire       : false
directDamage       : 130
instant            : true
explodeEffect      : NONE
tags               : 辐射
laserEffect        : true
color              : #8811FF11
lightSize          : 1
lightColor         : #FF119911
lightCastOnGround  : true
beamImage          : beam3.png
beamImageEnd       : beam1_end.png
beamImageStart     : beam1_start.png
beamImageOffsetRate: 1
instantReuseLast   : true
moveWithParent: true

speed            : 20
#spawnUnit       : test2


[movement]
moveSpeed:0.72

[ai]
buildPriority:0.8
