[core]
name:超时空尤里
price:50
radius:7
buildSpeed:5s
isBio:true
mass:100
strictLevel:0
armourMinDamageToKeep:0
armour:0
techLevel:1

maxHp:1000000

tags:Tech_1,Infantry,lives
displayDescription:用于减少重复工作的模板单位
displayDescription_ja = 重複作業を減らすために使用されるテンプレートユニット

transportSlotsNeeded:1


[graphics]
image:步兵基座.png
image_back:步兵身体(c).png
image_offsetY:-7
teamColorsUseHue:false

[attack]
canAttack:false
isFixedFiring:true
maxAttackRange:1000

[movement]
movementType:LAND
moveAccelerationSpeed: 0.3
maxTurnSpeed:3
reverseSpeedPercentage:0

moveDecelerationSpeed: 0.05
moveSpeed:0.9

#[hiddenAction_不屈]
#
#autoTrigger:if self.tags(includes='不屈')



[ai]
useAsAttacker:true


[turret_1]
x:                          0
y:                          0

[projectile_1]
life:                       1000
speed:                      114514
friendlyFire:               only-ignoreEnemy
areaDamage:                 -1145141919
areaRadius:                 30
instant:                    true
explodeEffect:              NONE
spawnUnit:test1

[action_special]
buildSpeed:                 0s
text:S.P.E.C.I.A.L.
alwaysSinglePress:          true
fireTurretXAtGround:        1


#alsoTriggerAction:qwq

#=========================================================================================


#[hiddenAction_qwq]
#
#clearAllWaypoints:true 
#addWaypoint_type:attack
#addWaypoint_maxTime:0.1s
#addWaypoint_target_nearestUnit_team:enemy
#addWaypoint_target_randomUnit_maxRange:5


