[core]
name:test1
radius:1
maxHp:114514
price:1000000
mass:1
energyMax:1


showOnMinimap:      false
isUnselectable:     true
disableAllUnitCollisions:       true
isUnselectableAsTarget:         true
canNotBeDirectlyAttacked:       true
canNotBeDamaged:                true
canNotBeGivenOrdersByPlayer:    true


[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:114514

[movement]
movementType:NONE

[graphics]
image:NONE.png


[action_i]
autoTriggerOnEvent:created

addWaypoint_type:attack
addWaypoint_maxTime:0.1s
addWaypoint_target_nearestUnit_tagged:lives

addWaypoint_target_nearestUnit_team:enemy
#alsoTriggerAction:ii

[hiddenAction_ii]
autoTrigger:if self.energy(equalTo=0)
deleteSelf:true



[turret_1]
x:0
y:0
canShoot:true
energyUsage:1
warmup:600

[projectile_1]
life:1000
directDamage:0
convertHitToSourceTeam:true
