[core]
copyFrom:ROOT:地球联合政府/坦克/装甲单位模板.ini,ROOT:unit-behaviors.template


name:览式坦克歼击车

price: 300
maxHp: 300
mass: 1200
buildSpeed: 15s
#availableInDemo: true
armour:3

radius: 13
displayRadius: 15

isBio: false


[graphics]
total_frames: 1
scaleImagesTo:22
image:览式坦歼.png

dustEffect: true

lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false

turretSize: 18
turretTurnSpeed: 3

isFixedFiring: true

maxAttackRange: 170
shootDelay: 45
turretRotateWithBody:true

[turret_1]
#
x: 0
y: 0
barrelX:5
invisible:true

projectile: 1

turnSpeedAcceleration:0

shoot_sound:cannon_firing
shoot_sound_vol:0.3
shoot_flame:large
shoot_light:#FFAAFFFF

canShoot: true
aimOffsetSpread:0
warmup:30

recoilOffset: -1
recoilOutTime: 3
recoilReturnTime: 9

[projectile_1]
life: 400
speed: 8
frame: 2
drawSize: 1
areaDamage: 400
areaRadius: 20
buildingDamageMultiplier:0.7
mutator1_ifUnitWithTags:tank
mutator1_directDamageMultiplier:2.2

largeHitEffect: true
targetGround: true

lightColor: #ffe92b
lightSize: 0.4


targetGroundSpread:10
lightCastOnGround: true

[movement]
movementType: LAND
moveSpeed: 1.1
moveAccelerationSpeed: 1.18
moveDecelerationSpeed: 1.25

maxTurnSpeed: 4
turnAcceleration: 0.2

moveSlidingMode :false
moveIgnoringBody:false





