[core]
dont_load:true
copyFrom:ROOT:地球联合政府/建筑/建筑模板.ini
@global ableToAddBuildSpeed:1
@memory resourceBuilding:unit[]     
#控制建造速度

[hiddenAction_initBuildSpeed]
autoTriggerOnEvent:created
setUnitMemory:nanoBuildSpeedMemory=1.5


[hiddenAction_changeBuildSpeed]
autoTrigger:if self.resource.maxFactories>=0 and self.resource.ifAbleToBan==0 and not self.hasFlag(id=31)
setUnitStats:nanoFactorySpeed=(memory.nanoBuildSpeedMemory+(memory.resourceBuilding.size)*(0.2))



[hiddenAction_buildspeedSub]
autoTrigger:if self.resource.maxFactories<0 and self.resource.ifAbleToBan==0
setUnitStats:nanoFactorySpeed=0.2
addResources:ifAbleToBan=1

[hiddenAction_buildspeedAdd]
autoTrigger:if self.resource.maxFactories>=0 and self.resource.ifAbleToBan==1 and not self.hasFlag(id=31)
addResources:ifAbleToBan=-1


#升级建造速度相关效果


[hiddenAction_addnanoByGift]
autoTrigger:if self.hp()==self.maxHp() and self.resource.Gift>100 and ${ableToAddBuildSpeed==1}
setUnitMemory:nanoBuildSpeedMemory=0.1+memory.nanoBuildSpeedMemory
addResources:Gift=-100


[hiddenAction_addnanoByGift1]
autoTrigger:if self.transportingCount(greaterThan=3)
setUnitMemory:nanoBuildSpeedMemory=1+memory.nanoBuildSpeedMemory
deleteNumUnitsFromTransport:4

#渲染 
[decal_error]
image:ROOT:/shared/错误.png
layer:onTop
onlyWhileAlive:true
isVisible:if self.hasFlag(id=31)

#检查加速

[hiddenAction_群体检测]
autoTrigger:true
takeResources_searchOnly:true
takeResources_includeUnitsWithinRange_team:own
takeResources_includeUnitsWithinRange:300
takeResources_maxUnits:1000
takeResources_triggerActionForEach:add
takeResources_excludeUnitsWithoutTags:oil
#setUnitMemory:resourceBuilding[]=[]

[hiddenAction_add]
requireConditional:if not memory.resourceBuilding.contains(thisActionTarget)
setUnitMemory:resourceBuilding[memory.resourceBuilding.size]=thisActionTarget
#单位数组
shrinkArrays:resourceBuilding


#资源
[global_resource_maxFactories]
hidden:false

[resource_ifAbleToBan]
hidden:true

[hiddenAction_addhpByExp]
autoTrigger:false


#其他

[movement]
movementType:BUILDING


[attack]
canAttack:false
