[core]
copyFrom   : ROOT:地球联合政府/步兵/t1步兵基础/t1步兵基础.ini,ROOT:unit-behaviors.template
name       : t1步兵
displayText: 基础步兵
displayDescription:[对地]\n-早期廉价的对地单位,但集群后火力同样凶猛\n-子弹关天,但人命廉价
displayDescription_ja = [Earth] \ n-hearly安い土地ユニットですが、クラスター\ n-bulletが閉じた後も火力も激しいですが、命は安いです

defineUnitMemory:float maxAttackRange
price:40

[hiddenAction_间谍伪装标签]
autoTrigger:true
temporarilyAddTags:可被间谍伪装,间谍外观_T1步兵

[graphics]
image_turret:步枪(c).png
turretImageScale:0.6



[attack]
maxAttackRange:80
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true
#isMelee:true
#meleeEngangementDistance:${attack.maxAttackRange}


[turret_1]
x:0
y:5
shoot_sound:missile_fire
shoot_light:#FFAA0000
recoilOffset:-3
recoilOutTime:2
recoilReturnTime:10
delay:30

[projectile_1]
life:100
directDamage:15

drawSize:0.7
lightSize:0.3
lightColor:#AAFF6666
speed:7
explodeEffect:smoke
image:子弹.png
[movement]
moveSpeed:0.72

[ai]
buildPriority:0.8


