[core]
copyFrom:ROOT:地球联合政府/步兵/t1步兵基础/t1步兵基础.ini,ROOT:unit-behaviors.template
name:t2风暴突击队
displayText:风暴突击队
displayText_ja:特殊部隊
displayDescription:[对地][可飞行][优秀反步兵/建筑]\n-特种部队的雏形,他们的武器对步兵伤害不错\n-可以埋设雷管以摧毁敌方建筑\n-可以通过滑翔翼飞行以跨越复杂地形
displayDescription_ja = [配信] [飛行] [優れた反輸送/建築] \ n-特殊部隊のプロトタイプ、彼らの武器は歩兵を傷つけます\ n-n-canは、複雑な地形にまたがる起爆装置に埋葬されます
maxHp:150
price:700
buildSpeed:25s
defineUnitMemory:boolean disappear
showOnMinimapToEnemies:false
energyMax:1
energyRegen:0.0005
selfRegenRate:0.05

[graphics]
image_turret:步枪(c).png
turretImageScale:0.6
image_back:风暴突击队身体.png
splastEffect:true


[attack]
maxAttackRange:120
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
showRangeUIGuide:true
isFixedFiring:false
#isMelee:true
#meleeEngangementDistance:80


[turret_1]
x:0
y:5
shoot_sound:missile_fire
shoot_light:#55FFFFFF
recoilOffset:-3
recoilOutTime:2
recoilReturnTime:10
delay:5

[projectile_1]
life:100
directDamage:10
color:#FFAAAAAA
lightColor:#FFAA0000
lightCastOnGround:true

[action_飞行斗篷]
buildSpeed:0s
price:energy=1,20
text:飞行斗篷
iconImage:滑翔.png
description_ja:動力グライダーで飛行が可能
description:支起一盏滑翔翼,帮助他跨越复杂的地形
convertTo:t2风暴突击队_光学迷彩

[action_putBoob]
text       : 放置炸弹
description: 放置一枚威力巨大的炸弹, 对各种单位都有很好的毁伤效果\n但要是爆炸前就被敌人摧毁就不好了
description_ja:1個$50の梱包爆薬を置く。複数人で投げ込めば強化バンカーでもひとたまりもない
iconImage:雷管.png
price      : 50,energy=0.5
fireTurretXAtGround:boom
buildSpeed:0.2s


[turret_boom]
x:0
y:0
image:空.png
projectile:boom
canShoot:false


[projectile_boom]
directDamage:0
life:100000
speed:5
image:雷管.png
targetGround:true
spawnUnit:雷管




[movement]
movementType:LAND
moveAccelerationSpeed: 1
maxTurnSpeed:3
reverseSpeedPercentage:0

moveDecelerationSpeed: 0.05
moveSpeed:0.9
turnAcceleration:10

