[core]
copyFrom:ROOT:地球联合政府/坦克/装甲单位模板.ini,ROOT:unit-behaviors.template
name:移动炮台车
displayText:移动炮台车
displayDescription:可以部署成一个机枪塔!高贵的tr玩家的最爱!
displayDescription_ja = 機関銃の塔に配備できます！ノーブルTRプレイヤーのお気に入り！
mass:1000
price:2000
maxHp:200
radius:15
buildSpeed:30s
dieOnConstruct:true
nanoRange:20
isBuilder:true
transportSlotsNeeded:4

[graphics]
image:移动炮台.png
scaleImagesTo:30
turretImageScale:1.5
dustEffect:true



[attack]
canAttack:false


[movement]
movementType:LAND
moveSpeed:0.8
moveAccelerationSpeed:0.1
moveDecelerationSpeed:0.1
reverseSpeedPercentage:0.4
maxTurnSpeed:2
turnAcceleration:1.2
moveSlidingMode:1


[action_1]
pos:0.1
text:展开
whenBuilding_rotateTo:270
convertTo:t1机枪塔
addResources:unsetFlag=1
whenBuilding_cannotMove:true
buildSpeed:5s
#[action_stop_forAi]
#text:停下当前行动
#autoTrigger:if self.isControlledByAI() and self.hp(lessThan=1500)
#
#alsoQueueAction:run_forAi

